### ISSUE TITLE
Minimap icons

### ISSUE THREAD

**Issue by BrokenWyvern** [NuovaPrime/DBT-Issues#10]
Describe the bug: Hair is glitched on minimap character display

To Reproduce List the steps to reproduce the issue: N/A

Other Mods: HERO's
![Terraria_ Cthulhu is mad  and is missing an eye! 10_17_2020 8_45_15 PM](https://user-images.githubusercontent.com/64664491/96356245-d09ee300-10b9-11eb-8aa8-910693aebdb6.png)

**Comment by NuovaPrime** [comment]
Fixed.
