### ISSUE TITLE
Game Crash when going into LSSJ

### ISSUE THREAD

**Issue by Beandip69** [NuovaPrime/DBT-Issues#13]
**Describe the bug**
When going into LSSJ using the form selector item, I got a game crash.

**To Reproduce**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/73091219/96404698-6b69f100-1190-11eb-9630-c9a7c807c034.png)

**Other Mods**
HERO's Mod, Webmilio Commons

**Additional Info**
n/a

**Comment by Tyndareus** [comment]
Need the log for crashes, not an exception.

There also appears to be steps missing for this unless its something added by nuovas overload change, can't reproduce in my current branch

**Comment by NuovaPrime** [comment]
Old, probably fixed.
