### ISSUE TITLE
Legendary trait | ki gets yeeted if you transform

### ISSUE THREAD

**Issue by Lefucker** [NuovaPrime/DBT-Issues#15]
**Describe the bug**
Using any form with the legendary trait will immediately reduce your ki to 50% if you were previously above that threshold.

**To Reproduce**
Get the legendary trait, use a form while above 50% ki and watch your ki fade away.

**Screenshots**
N/A

**Other Mods**
Cheat Sheet

**Additional Info**
N/A

**Comment by ChristmasGuyyy** [comment]
its not just forms, any ki attack will do that too.

**Comment by zszeta** [comment]
Has to do with 2x ki perk of legendary trait. Logang said something about it but i cant remember

**Comment by Tyndareus** [comment]
Fixed
