### ISSUE TITLE
Power wish only gives Ki

### ISSUE THREAD

**Issue by Preston17gu** [NuovaPrime/DBT-Issues#16]
**Describe the bug**
The wish of "power" says it will increase max health, ki, and damage. However, only Ki is increased upon wishing.

**To Reproduce**
Just get the Dragon Balls and wish for power.

**Screenshots**
N/A

**Other Mods**
Hero's Mod

**Additional Info**
N/A

**Comment by Tyndareus** [comment]
Fixed but wont be in until my UI changes are done
