### ISSUE TITLE
Game crashed when pressing Charge key.

### ISSUE THREAD

**Issue by ChristmasGuyyy** [NuovaPrime/DBT-Issues#17]
**Describe the bug**
I pressed the C key, and the game crashed. i dont have an idea of what could have caused this.

*To Reproduce**

**Screenshots**
![dbtcrash1](https://user-images.githubusercontent.com/73090750/96458176-3e482d80-11e6-11eb-937d-967740ea3186.jpg)

**Other Mods**
Heroes Mod.

**Additional Info**

**Comment by Tyndareus** [comment]
Should be fixed, would have been better if mentioned if you were on an old character rather than a new character.
