### ISSUE TITLE
Ki regening and decreasing while charging in stationary flight

### ISSUE THREAD

**Issue by ChristmasGuyyy** [NuovaPrime/DBT-Issues#19]
**Describe the bug**
While boost flying, staying still can both increase and decrease ki.
**To Reproduce**
staying still and boost flying makes ki increase, but moving around for a amount of time starts to make ki go down when stationary instead.
**Screenshots**
https://cdn.discordapp.com/attachments/736073423977054230/767810798940323870/Desktop_2020.10.19_-_13.04.57.03.mp4

**Other Mods**
Heroes mod.

**Additional Info**

**Comment by ChristmasGuyyy** [comment]
turns out its just poopy terraria code lmao

**Comment by NuovaPrime** [comment]
Not a bug.
