### ISSUE TITLE
Potential Unlocked Keeps Ki Constant

### ISSUE THREAD

**Issue by Pika-Codes** [NuovaPrime/DBT-Issues#21]
When you go into the potential unlocked form, your ki drains for a few seconds, then remains static, until you charge, where wit increases a small amount, where it remains static as long as you're charging, but when you stop, it drops back to the lower static number again.

To reproduce, go into Potential Unlocked with the prodigy trait, it probably works on other traits, but I haven't tested them yet.

The video demonstrating the problem is here: [https://youtu.be/A77z99In-mo](https://youtu.be/A77z99In-mo)

The other mod I had were: Veinminer and HERO's mod

**Comment by AetherBreaker** [comment]
Something I believe it related to this is that all forms except kaioken and ssj1

 seem to drop your ki down to a certain number, on new characters looks to be around 500 and wont let you regen past said point, as if its temporarily setting your max ki down to that number, no methods of gaining max ki seem to affect it EXCEPT the ki adder and ki remover test items. not even the ki filler can fill your ki past the "max" amount that the form seems to want to use

https://youtu.be/4wjZGw3cLYs

**Comment by Tyndareus** [comment]
That issue only affected legendary which is fixed, if you check the closed bugs.
This ones something else, though couldn't get it to happen on a new character or an existing dbt character.

**Comment by NuovaPrime** [comment]
You probably had the perfect amount of ki regen, but old bug so closing it anyways.
