### ISSUE TITLE
Weird Red laser thingy overlaying character

### ISSUE THREAD

**Issue by ChristmasGuyyy** [NuovaPrime/DBT-Issues#24]
**Describe the bug**
when transforming up a short animation might play, charging aura doesnt appear either. you also cant transform.

**To Reproduce**
use trans clearer and power up to evil ss3 at the same time, another way is to transform up right after loading into a world.
**Screenshots**
![image](https://user-images.githubusercontent.com/73090750/96523430-50a08680-123b-11eb-93d9-b04c296a14a0.png)

**Other Mods**
Heroes Mod.

**Additional Info**
Add any other context or information about the problem here.

**Comment by ChristmasGuyyy** [comment]
well i found the actual cause.

**Comment by NuovaPrime** [comment]
Fixed.
