### ISSUE TITLE
Maybe a bug? Charging slows mounts.

### ISSUE THREAD

**Issue by Preston17gu** [NuovaPrime/DBT-Issues#25]
**Describe the bug**
Charging while on a mount slows it down just like charging while walking. I could see the being intentional, and I could see it not. Might as well report it.

**To Reproduce**
Charge while moving on a mount.

**Screenshots**
N/A

**Other Mods**
Hero's

**Additional Info**
N/A

**Comment by NuovaPrime** [comment]
Intentional.
