### ISSUE TITLE
Divine Zenkai keeps activating.

### ISSUE THREAD

**Issue by Preston17gu** [NuovaPrime/DBT-Issues#32]
**Describe the bug**
The Divine Zenkai keeps activating no matter what. It activates, lasts a minute, then cools down for 2. Right after the cool down it activates immediately again.

**To Reproduce**
Seemingly, just play a divine character.

**Screenshots**
N/A

**Other Mods**
Hero's

**Additional Info**
N/A

**Comment by Tyndareus** [comment]
Was fixed before this was found, sorry bruh
