### ISSUE TITLE
Overload Animation Flickering

### ISSUE THREAD

**Issue by zszeta** [NuovaPrime/DBT-Issues#33]
**Describe the bug**
The big green overload sprite flickers when spamming ki weapons like hellzone and celestial rapture

**To Reproduce**
Build up Overload
Either before or right when it starts, spam a ki weapon (I'm assuming something that fires a lot of blasts) 
Keep spamming during the whole animation and observe

**Screenshots**
_(excuse the music in background, I keep forgetting my recorder captures that)_
https://streamable.com/hnpxv1

**Other Mods**
Hero's

**Additional Info**
This only happens when you start spamming the weapon before, when it starts, and _slightly_ after. During the end or in the middle, spamming a weapon wont cause the flickering.

**Comment by NuovaPrime** [comment]
Weird edge case issue, might be fixed already, check on latest build if it still applies.
