### ISSUE TITLE
Trait changing wish requires relog.

### ISSUE THREAD

**Issue by Preston17gu** [NuovaPrime/DBT-Issues#34]
**Describe the bug**
If you change your trait with the Dragon Balls, your forms list will not update, and will only allow you to select forms from your previous trait, which you can't transform into anymore. The issue is fixed upon relogging, so it's very minor.
Eg: Divine Trait. Open menu. See Rose and BoL. Wish change to Prodigy. Open menu. Still see Rose and BoL.

**To Reproduce**
Change your trait with the Dragon Balls, then open your forms menu.

**Screenshots**
![Screenshot (105)](https://user-images.githubusercontent.com/73049424/96825435-1e3f8680-13ff-11eb-8a71-7fd47f12258c.png)
(Traitless while displaying Rose and BoL)

**Other Mods**
Hero's

**Additional Info**
I don't believe this was in the last version we had. Could be crazy though.

**Comment by Tyndareus** [comment]
Closing this due to it being the old UI.
