### ISSUE TITLE
ssjb transformation animation (VISUAL BUG)

### ISSUE THREAD

**Issue by Vectard** [NuovaPrime/DBT-Issues#36]
**Describe the bug**
the animation for entering ssjb has some weird lines

**To Reproduce**
go ssjb
![tModLoader_zETyUFQP1z](https://user-images.githubusercontent.com/73315106/96934746-c3566f80-1490-11eb-98e4-292dc0669537.png)

**Screenshots**

**Other Mods**
cheatsheet

**Additional Info**

**Comment by NuovaPrime** [comment]
Should be fixed.
