### ISSUE TITLE
Kaioken and wrathful changing haircolor

### ISSUE THREAD

**Issue by AetherBreaker** [NuovaPrime/DBT-Issues#42]
Kaioken, and Wrathful change your hair color to a color I can only describe as matching the guides.
Potential unlocked does this aswell, but it seems to do it only when the form is triggered using the testing item.

![tModLoader_cHbYflFmIC](https://user-images.githubusercontent.com/47284836/97003889-2fc18500-150a-11eb-91a7-a9bf2570b545.png)
![Jss58HNqU6](https://user-images.githubusercontent.com/47284836/97003924-3a7c1a00-150a-11eb-94cb-60928f44e25d.png)
![OwIIlKB83O](https://user-images.githubusercontent.com/47284836/97003935-3d770a80-150a-11eb-9247-3c0c8819558e.png)
![exU9hdan6U](https://user-images.githubusercontent.com/47284836/97003942-3f40ce00-150a-11eb-9bdc-ee146540db83.png)
![tgr1U24p1G](https://user-images.githubusercontent.com/47284836/97003946-410a9180-150a-11eb-81ef-35a37564bece.png)

This has been consistent on two different characters, both with hair color set to black during character creation, and both with goku hair selected after loading into a world
I've so far only tested this with Legendary trait, don't know if any other forms are doing this

**Comment by Tyndareus** [comment]
Fixed
