### ISSUE TITLE
Dragon Pedestal will not spawn in new worlds

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#46]
**Describe the bug**
Any world you create after the first will not spawn a dragon pedestal.

**To Reproduce**
Create a new world and the dragon pedestal will be present. Any world created after the first will not contain a dragon pedestal until you restart your game.

**Other Mods**
Hero's Webmilio's common

**Comment by Tyndareus** [comment]
Fixed
