### ISSUE TITLE
Traits changed by dragon pedestal

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#47]
**Describe the bug**
Leaving a world after collecting all the dragon balls will occasionally change other character's traits.

**To Reproduce**
Collect all 7 dragon balls, but leave them at the pedestal and do not summon Shenron. Leaving and rejoining that world will cause different character's traits to be changed occasionally.(By different characters I mean any other character that you did not use to log into the world with.) 

**Other Mods**
Hero's Webmilio's common

**Additional Info**
This also caused my game to crash on the second attempt. The dragon balls will also not be at the pedestal after a game restart, not sure if this is intended.

**Comment by Tyndareus** [comment]
A crash requires that the log is posted

**Comment by Tyndareus** [comment]
Should be fixed
