### ISSUE TITLE
Events like the goblin army do not progress

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#49]
**Describe the bug**
Events do not progress past 0 when killing enemies.

**To Reproduce**
Summon any event and kill an enemy that it spawns.

**Other Mods**
Webmilio's common Hero's

**Additional Info**
I've tested this with the pirates and goblins, but I'm assuming it extends to all events.

**Comment by Tyndareus** [comment]
Fixed
