### ISSUE TITLE
Triggering overload at the top of the map cancels the animation.

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#50]
https://user-images.githubusercontent.com/77537537/104942202-21a4c880-5982-11eb-89c5-65d09ed64ca9.mp4

**Describe the bug**
Overloading while at the very top of the map cancels the overload animation completely.

**To Reproduce**
Fly to the very top of the map and activate overload.

**Other Mods**
Webmilio's common Hero's
[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5831148/client.log)

**Comment by NuovaPrime** [comment]
Terraria deletes any projectiles that go outside the map borders, not something we can fix.
