### ISSUE TITLE
Gravity Chamber failing to spawn after first world.

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#53]
**Describe the bug**
The gravity chamber will not spawn in any world after your first. To fix this I had to restart my game then create a new character and world.

**To Reproduce**
Create and world and the gravity chamber will be present. It will not be in any world after that. 

**Other Mods**
Webmilio's common Hero's

[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5831490/client.log)

**Comment by Tyndareus** [comment]
Fixed
