### ISSUE TITLE
Flying while summoning Shenron causes many issues

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#54]
**Describe the bug**
Flying around after summoning Shenron causes visual bugs. This also caused him to be spawned in twice in one instance. 

**To Reproduce**
Fly around after summoning Shenron

**Screenshots**
![error](https://user-images.githubusercontent.com/77537537/104952014-ac40f400-5991-11eb-81eb-1a26da4667ac.png)

https://user-images.githubusercontent.com/77537537/104952152-f1fdbc80-5991-11eb-84a4-cb0c330e8f01.mp4

[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5831937/client.log)

**Other Mods**
Web's Hero's

**Additional Info**
After trying to make my wish my game crashed.

**Comment by NuovaPrime** [comment]
Solution added.
