### ISSUE TITLE
Minor aura visual bug underwater

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#58]
**Describe the bug**
Aura underwater has some minor visual bugs when pressing against blocks.

**To Reproduce**
Have any aura around your character, then go underwater and press against the floor or walls.

**Screenshots**

https://user-images.githubusercontent.com/77537537/105122129-a20f1a80-5aa3-11eb-8e90-4286c0c73206.mp4

**Other Mods**
Hero's Web's

**Additional Info**
Hypernova also causes some visual bugs when activated under or near water.

**Comment by Tyndareus** [comment]
thats most likely because the sprite is no longer in the water so the processing stack doesn't apply (it inherits the dirt/block lighting etc)

**Comment by NuovaPrime** [comment]
Not fixable, nor really an issue.
