### ISSUE TITLE
Not choosing a hairstyle causes a game crash

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#61]
**Describe the bug**
If you exit the world without choosing a hairstyle, your game will crash every time.

**To Reproduce**
Create a new character and load into a world. Don't choose a hairstyle and leave the world. Attempting to rejoin will cause a game crash.
[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5845344/client.log)

**Other Mods**
Hero's Web's

**Comment by Tyndareus** [comment]
Check again whenever the next build is out

**Comment by Louis0-0** [comment]
Build released today still has this bug.

[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5863815/client.log)

**Comment by Tyndareus** [comment]
Theres no actual error from dbt though, and testing works for me
