### ISSUE TITLE
FFship can take damage when shielding

### ISSUE THREAD

**Issue by Louis0-0** [NuovaPrime/DBT-Issues#65]
**Describe the bug**
You can damage the ffship in certain spots while it's shielding.

**To Reproduce**
Attack the ffship with ki blasts in the bottom corners area shown in the video.

**Screenshots**

https://user-images.githubusercontent.com/77537537/105568442-3cbb6380-5d07-11eb-93e7-9cf2ac5c088f.mp4

**Other Mods**
Hero's Web's

**Additional Info**
You can damage the ship from both the bottom left and bottom right corners. I tested this with super energy barrage and energy blast barrage.
[client.log](https://github.com/NuovaPrime/DBT-Issues/files/5859650/client.log)

**Comment by Errick-Schumacher-Kennedy** [comment]
Can confirm that bottom left and bottom right corners are vulnerable, same goes for the top left and right. I used Super Energy Barrage + Energy blast barrage, as well as a minishark to test if direct attacks were also affected and a Meowmere to see if the projectile of it will get hit. Yoyos don't seem to do damage to the corners.

**Comment by Louis0-0** [comment]
fixed
