### ISSUE TITLE
Big Bang Attack deals damage against NPCS.

### ISSUE THREAD

**Issue by Errick-Schumacher-Kennedy** [NuovaPrime/DBT-Issues#66]
**Describe the bug**
After shooting Big Bang Attack at an NPC directly, the NPC will suffer damage and Knockback.

**To Reproduce**
1. Aim Big Bang Attack at NPC
2. Shoot and observe.
Note: Has to be direct. AoE does nothing.

**Screenshots**
![ezgif-3-6a8b53dc8f6a](https://user-images.githubusercontent.com/68740966/105571793-e34a4780-5d8d-11eb-8ad8-5b4e1a99938c.gif)
**Other Mods**
Hero's Mod

**Additional Info**
Add any other context or information about the problem here.

**Comment by Skipping903** [comment]
Big bang attack isn't finished

**Comment by Skipping903** [comment]
Fixed this anyways
