### ISSUE TITLE
Pedestal makes terrarians phase through blocks

### ISSUE THREAD

**Issue by LordSami** [NuovaPrime/DBT-Issues#68]
**Describe the bug**
Whenever I walk against a pedestal 2 blocks higher than the level I'm on I phase through the blocks below

**To Reproduce**
Walk against a pedestal 2 blocks higher off the ground

**Screenshots**
![20210125133932_1](https://user-images.githubusercontent.com/48102994/105725842-14637d00-5f32-11eb-9d5a-475934f6747f.jpg)

**Comment by NuovaPrime** [comment]
Terraria thing, that's a hoik.
