### ISSUE TITLE
Confusion Has No Effect While Flying

### ISSUE THREAD

**Issue by zszeta** [NuovaPrime/DBT-Issues#70]
**Describe the bug**
When under the Confusion debuff, the reversed controls effects do not apply when flying, but work fine when not flying.

**To Reproduce**
Attain the Confusion debuff and start flying. Move around and you'll notice the controls are not reversed and your flight speed is reduced.

**Screenshots**
Visualization of the mind

**Other Mods**
Hero's. 

**Additional Info**
Flight speed is also decreased while flying under the Confusion debuff
Character sprite is the only thing that flips when flying.

**Comment by NuovaPrime** [comment]
I won't make it reverse controls, but I may just make it slow you down heavily while confused.

**Comment by NuovaPrime** [comment]
Fixed in next update.
