### ISSUE TITLE
Electricity Not Rotating Correctly [VISUAL BUG]

### ISSUE THREAD

**Issue by zszeta** [NuovaPrime/DBT-Issues#8]
**Describe the bug**
The electricity in forms that have it do not rotate correctly with the character when flying

**To Reproduce**
Go into a form with electricity in it
Fly around and observe

**Screenshots**
![bug1](https://user-images.githubusercontent.com/68525620/96353025-33be5480-107d-11eb-948a-ba8164d95f1d.JPG)
![bug 2](https://user-images.githubusercontent.com/68525620/96353026-35881800-107d-11eb-8386-ce8eab3a3f93.JPG)

**Other Mods**
Hero's Mod and Boss Checklist, but shouldn't have any relation to issue

**Additional Info**
Nada.

**Comment by zszeta** [comment]
The transforming and power down animations also don't rotate correctly when flying.

**Comment by NuovaPrime** [comment]
Should be fixed.
